<#
.SYNOPSIS
  Walk community/CAPTURE_QUEUE.md, extract URL + target + topics for every
  row, and emit a single PROMPTS.md file with one ready-to-copy prompt
  block per URL.

.DESCRIPTION
  No hand-editing: pete picks the section he's about to capture, copies the
  prompt block, pastes it into the Claude for Chrome extension on the
  matching page. The prompt has the URL, today's date, the suggested topic
  tags, and the trust level pre-filled.

  Output: homecoming-build-companion/inbox/PROMPTS.md
#>
[CmdletBinding()]
param(
    [string]$Queue = (Join-Path $PSScriptRoot '..\..\homecoming-build-companion\community\CAPTURE_QUEUE.md'),
    [string]$Out   = (Join-Path $PSScriptRoot '..\inbox\PROMPTS.md')
)

$ErrorActionPreference = 'Stop'
$Queue = [System.IO.Path]::GetFullPath($Queue)
$Out   = [System.IO.Path]::GetFullPath($Out)
if (-not (Test-Path $Queue)) { throw "CAPTURE_QUEUE.md not found at $Queue" }
$outDir = Split-Path $Out -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

# Parse table rows. Two supported forms (old without Status, new with Status
# from update-queue-status.ps1):
#   old:  | 1   | [Title](URL) | `target/file.md` | tag1, tag2 | trust |
#   new:  | ✅ done | 1 | [Title](URL) | `target/file.md` | tag1, tag2 | trust |
# Both flow through the same regex by making the leading "Status" cell optional.
$rxRow = '^\|\s*(?:[^\|]*\|\s*)?(?<n>\d+)\s*\|\s*\[(?<title>[^\]]+)\]\((?<url>https?://[^\)]+)\)\s*\|\s*`(?<target>[^`]+)`\s*\|\s*(?<topics>[^|]+?)\s*\|\s*(?<trust>[^|]+?)\s*\|'

$lines = Get-Content $Queue
$rows = foreach ($line in $lines) {
    if ($line -match $rxRow) {
        [pscustomobject]@{
            n      = [int]$Matches['n']
            title  = $Matches['title'].Trim()
            url    = $Matches['url'].Trim()
            target = $Matches['target'].Trim()
            topics = ($Matches['topics'] -split ',' | ForEach-Object { $_.Trim() }) -join ', '
            trust  = $Matches['trust'].Trim()
        }
    }
}

if (-not $rows) { throw "No rows parsed from $Queue. The table format may have changed." }

# Build the file as one big here-string. Each entry: anchor, copy block, hint.
$today = Get-Date -Format 'yyyy-MM-dd'
$header = @"
# Pre-generated extraction prompts

<!-- markdownlint-disable -->
<!-- Generated by scripts/generate-prompts.ps1; prompt blocks are verbatim
  copy/paste payloads and are not hand-lint-fixed. -->

One ready-to-copy prompt per row in [CAPTURE_QUEUE.md](../../homecoming-build-companion/community/CAPTURE_QUEUE.md).

Workflow per row (full instructions in [CAPTURE_WORKFLOW.md](../scripts/CAPTURE_WORKFLOW.md)):

1. Click the URL → opens forum thread in Chrome.
2. Open the Claude for Chrome side panel (extension icon, top right of Chrome).
3. Copy the prompt block below into the side panel chat → send.
4. Copy Claude's response (whole assistant message).
5. In PowerShell: ``& "`$env:USERPROFILE\repos\homecoming-build-companion\scripts\capture.ps1" -Paste``

The prompt fills in the URL, today's date ($today), the topic tags, and trust level for that specific guide. Don't edit anything — paste verbatim.

Total in queue: **$($rows.Count)** captures.

---

"@

# Outer and inner code-fence variables — use ~~~ for the outer container so we
# can put real ``` (markdown fence) inside without any PowerShell escape gymnastics.
$F3 = [string]::new([char]0x60, 3)   # three literal backticks

$blocks = foreach ($r in $rows) {
@"

## $($r.n). $($r.title)

- **URL:** <$($r.url)>
- **Target:** ``$($r.target)``
- **Topics:** $($r.topics)
- **Trust:** $($r.trust)

Copy everything between the ~~~ markers below and paste it into the Claude for Chrome side panel:

~~~
You're reading a Homecoming City of Heroes forum thread. Extract it into a
markdown file matching the format below.

IMPORTANT — multi-post guides. Many threads spread the guide across several
sequential posts by the same author (post 1: intro / table of contents,
post 2: section A, post 3: section B, ...). Walk the entire thread and
treat ALL posts by the original poster (and any users the OP explicitly
names as co-authors) as one continuous guide. Concatenate them in
chronological order, preserving the OP's section structure and headings.
If the OP edits a post over time, capture the latest version.

Replies from other users are community discussion. Include them only if
they materially correct, extend, or codify the guide content — and
attribute clearly ("as @user noted in reply 17, ..."). Skip flames,
signatures, brief praise, off-topic chatter.

URL: $($r.url)

# Frontmatter rules (apply to every emitted block below)
# - ``trust:`` is exactly one of: first-party, community-consensus, single-author-opinion.
#   Forum user-rank labels (Members, Retired Community Rep, etc.) are not valid trust values.
# - ``authors:`` is a single-line YAML array, e.g. [Bopper, tidge].
#   Single-line keeps the index parser happy.
# - All listed keys are required.

# Embedded builds — capture each as its own block

When the thread contains a complete build dump — a "Hero Plan" / "Villain Plan"
forum-export block, a [b]Hero Plan...[/b] BBCode block, or a DataLink URL —
extract it as a SEPARATE markdown block in the response, after the parent
capture. Each build is its own loadable artifact and gets its own file when
the user ingests, so it carries enough context to stand alone.

If the thread contains zero embedded builds, emit only the parent capture
and skip the per-build blocks entirely.

# Required output

Emit one PARENT capture block, immediately followed by zero or more BUILD
sub-capture blocks. Use the templates exactly. Output only fenced markdown
blocks, no other commentary.

## Block 1 — PARENT capture

$($F3)markdown
---
title: $($r.title)
url: $($r.url)
source: forums.homecomingservers.com
authors: [<every author whose content you included>]
date_posted: <OP's first-post date, YYYY-MM-DD, or unknown>
date_captured: $today
captured_by: local-capture
topic_tags: [$($r.topics)]
trust: $($r.trust)
multi_post: <true | false>
post_count: <number of OP/co-author posts you concatenated, e.g. 1, 4, 12>
contradicts_data: <none | "claim X conflicts with data/Y.json — see notes">
---

## Summary

3-5 bullet conclusions covering the WHOLE guide (not just the first post).
State the conclusions; don't tease.

- Top-line claim 1
- Top-line claim 2
- Top-line claim 3

## Verbatim excerpt

> Substantive paragraphs from the OP's posts in chronological order.
> If the guide spans multiple posts, mark each with a heading like
> "### Post 2 — Section: <name>" so the original structure is preserved.
> Trim with [...] inside long passages; preserve every section.

## Notable replies (only if materially additive)

- @user_name (date) — one-line summary of the contribution + verbatim excerpt.

## Build attachments

List every embedded build emitted in Block 2+ below, plus any unattached
build references (DataLink-only, .mxd attachments, etc.). When the thread
contains no embedded builds, the section is empty.

- <build title> — see Block <N> below — file: builds/<at>/<slug>.md — <archetype>, <primary>/<secondary>, <one-line summary>
- DataLink only (no full export): <verbatim URL> — importable via MidsReborn Ctrl+I
- .mxd file attachment: <filename> — referenced in the OP; the file itself is not retrieved by this capture
$F3

## Block 2+ — BUILD sub-capture (repeat once per embedded build)

$($F3)markdown
---
title: <build name from the post, or "<AT>/<Primary>/<Secondary> — <theme>">
parent_guide: <relative path to the parent capture, e.g. archetypes/blaster/<slug>.md>
parent_url: $($r.url)
post_url: <URL of the specific post containing this build, with #post-N anchor when available>
build_author: <forum handle who posted this specific build>
date_posted: <YYYY-MM-DD of the post containing the build>
date_captured: $today
captured_by: local-capture
archetype: <Tanker | Brute | Scrapper | Stalker | Sentinel | Blaster | Corruptor | Defender | Controller | Dominator | Mastermind | Peacebringer | Warshade | Arachnos Soldier | Arachnos Widow>
primary: <powerset name as it appears in the build>
secondary: <powerset name>
ancillary: <ancillary / patron pool name, or "none">
build_goal: <one phrase, e.g. "soft-cap defense", "max damage", "perma-Hasten farmer">
build_format: <forum-export | datalink | mxd | mixed>
verified: false
contradicts_data: <none | flag>
suggested_filename: builds/<archetype-lowercase>/<slug>.md
---

## Context

2-4 sentence summary covering: what the parent guide says about this build,
why it exists, what it's optimized for, when to use it. Pull the context
from the parent guide so this file reads cleanly on its own.

## Verbatim build

The complete forum-export block, BBCode and all, copied verbatim from the
post. Preserve the source formatting. The block speaks for itself; the user
pastes it into MidsReborn directly.

## DataLink

When the post includes a DataLink URL, paste it verbatim here. Omit the
section when no DataLink is posted.

## Notes from the author (if any)

Author commentary that accompanies the build in the same post, copied
verbatim. Omit the section when no author commentary is present.
$F3

After Claude responds, copy its message and run:

~~~powershell
& "`$env:USERPROFILE\repos\homecoming-build-companion\scripts\capture.ps1" -Paste
~~~

---
"@
}

$content = $header + ($blocks -join "`r`n")
Set-Content -Path $Out -Value $content -Encoding UTF8

$bytes = (Get-Item $Out).Length
Write-Host "Wrote $Out  ($([math]::Round($bytes/1KB,1)) KB; $($rows.Count) prompt blocks)" -ForegroundColor Green
